### ISSUE TITLE
Attempting to include 3.6.1 via jitpack fails with 401, due to VJSON not being public

### ISSUE THREAD

**Issue by ZenDarva** [Valkryst/VTerminal#105]
Title covers the issue.  Attempting to use VTerminal, with Java8, Gradle 5.2.1, and jitpack.  According to the JitPack documentation, this is a result of the VJSON repository not being public, which seems reasonable, since I don't see it in your list of repositories, and if I try to construct the URL manually, i get a 404.

I tested back through 3.5.5, all versions I tested displayed the same issue.

build.gradle
`repositories {
    mavenCentral()
            maven{
                url "https://jitpack.io"
            }

}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    implementation 'com.github.Valkryst:VTerminal:3.6.1'
}`

Relevant output from Gradle.

`> Task :compileJava FAILED
Failed to get resource: GET. [HTTP HTTP/1.1 401 Unauthorized: https://jitpack.io/com/github/Valkryst/VJSON/d3313e4/VJSON-d3313e4.pom)]
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/com/github/Valkryst/VJSON/d3313e4/VJSON-d3313e4.pom]
Resource missing. [HTTP HEAD: https://repo.maven.apache.org/maven2/com/github/Valkryst/VJSON/d3313e4/VJSON-d3313e4.jar]
:compileJava (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 1.97 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.github.Valkryst:VJSON:d3313e4.
     Required by:
         project : > com.github.Valkryst:VTerminal:3.6.1
      > Could not resolve com.github.Valkryst:VJSON:d3313e4.
         > Could not get resource 'https://jitpack.io/com/github/Valkryst/VJSON/d3313e4/VJSON-d3313e4.pom'.
            > Could not GET 'https://jitpack.io/com/github/Valkryst/VJSON/d3313e4/VJSON-d3313e4.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.`

**Comment by Valkryst** [comment]
Thanks for submitting an issue about this! 

I'll have a fix implemented, and new version pushed, later tonight

**Comment by Valkryst** [comment]
@ZenDarva 

I've created a quick, temporary fix and uploaded it as version "2020.02.09-break-alpha". Let me know if this works for you, or if any issues arise.

I'll be working on a new version of VTerminal throughout the rest of this month.
