### ISSUE TITLE
Cannot resolve plugin org.apache.maven.surefire:surefire:3.0.0-M4

### ISSUE THREAD

**Issue by Andres6936** [Valkryst/VTerminal#109]
The compilation process with Intellij IDEA 2020.3 throws the error:

`Cannot resolve plugin org.apache.maven.surefire:surefire:3.0.0-M4`

**Comment by Valkryst** [comment]
It's safe to remove the surefire plugin from your `pom.xml` file. It's only necessary for automated testing and it will be removed in the next version of VTerminal.

Let me know if that fixes the issue for you 👍

**Comment by Andres6936** [comment]
I'm not very versed in Maven, however, while looking for a solution to the problem I found that Surefire is one of the dependencies of the stages of Maven to be able to generate the JAR with all the dependencies included, so, it will not be possible to remove Surefire from the pom.xml

**Comment by Andres6936** [comment]
I have created a PR (#110) that gives a solution to the above mentioned problem and several other problems, but this time caused with the resource load.

**Comment by Valkryst** [comment]
Merged PR #110. Thank you for taking the time to create a PR which resolves the issue

**Comment by Andres6936** [comment]
No, I thank you very much for accepting the PR.
