### ISSUE TITLE
Is possible minimize the screen to the system tray?

### ISSUE THREAD

**Issue by tiaggofg** [Valkryst/VTerminal#225]
Hi!

Can I minimize a screen to the windows/linux system tray?

![image](https://github.com/Valkryst/VTerminal/assets/84431015/61b35370-bb78-4cae-8aa1-750853382e72)

**Comment by Valkryst** [comment]
Hey,

Yup! The following links should help you to figure it out. I'd show you myself, but my computer's currently under repair:

- https://docs.oracle.com/javase/tutorial/uiswing/misc/systemtray.html
- https://stackoverflow.com/questions/7461477/how-to-hide-a-jframe-in-system-tray-of-taskbar
