### ISSUE TITLE
Fail to compile example

### ISSUE THREAD

**Issue by Andres6936** [Valkryst/VTerminal#75]
I am trying to compile the first example of the wiki, but I get an error from the IDLE I use (_Intellij IDEA 2017.2.5_).

![imagen](https://user-images.githubusercontent.com/18540634/31055747-0d25c252-a68d-11e7-987a-773c9fc14f4b.png)

La version del JAR que utilizo para compilar el ejemplo es: **VTerminal-2.5.0-BETA.jar**

**Comment by Valkryst** [comment]
Try adding this to your Maven pom file, let me know if it helps:

```
<dependency>
    <groupId>com.github.Valkryst</groupId>
    <artifactId>VRadio</artifactId>
    <version>1.2.0</version>
</dependency>
```

**Comment by Andres6936** [comment]
Good morning......

In fact, the code section is already included in the **MAVEN POM file**, however, when compiling from the source it compiles well and without errors, but when testing the generated JAR it jumps errors related to the VRadio classes.

**Comment by Valkryst** [comment]
That is an interesting error. I've built a new Jar file that should include all required dependencies and files. Give this a shot, it may fix the issue!

https://github.com/Valkryst/VTerminal/releases/tag/2.5.0-BETA-2

**Comment by Andres6936** [comment]
Interestingly, the JAR now works and compiles correctly.

Thanks for the quick response.

**Comment by Valkryst** [comment]
Awesome. Thanks for helping me figure out the issue, I rarely use the JAR, so I wouldn't have caught this issue so soon.
